### ISSUE TITLE
Support formatting to string in addition to print_oi

### ISSUE THREAD

**Issue by dramforever** [jeffswt/pydatagen#2]
Now `print_oi` directly sends the data to stdout. It would be nice if one could get the formatted string instead.

**Comment by jeffswt** [comment]
`print_oi` function dropped in favour of plain `printf`.

Modifed since 537217ba8f37b3a03be91cc0761d917a0be0fa1d.

If you believe that formatting strings really are useful, feel free to reopen this issue.
