### ISSUE TITLE
kw argument `distinct` is not documented in `randlist`

### ISSUE THREAD

**Issue by xmcp** [jeffswt/pydatagen#4]
by the way, 

``` python
>>> random.sample([1,2,3,4,5], 3)
[3, 4, 1]
```

**Comment by jeffswt** [comment]
**Useless** function removed, so there is no necessity to talk around this issue any more.

Fixed since 537217ba8f37b3a03be91cc0761d917a0be0fa1d.

If you believe that this is useful, feel free to reopen this issue, make a PR or simply edit the code.
